name=Pynter
version=0.0.1
author=angelsl
maintainer=angelsl <dont@email.me>
sentence=PVML interpreter
paragraph=Pynter is a fork of Sinter, an interpreter for SVML. PVML, Pynter's own bytecode format, is currently identical to SVML.
category=Other
url=https://github.com/source-academy/pynter
architectures=*
